name: PHP Quality & Tests

on:
  push:
    branches: '**'
  pull_request:

jobs:
  test:
    name: Run Unit Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['8.0', '8.2']
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: gd, mysqli, opcache, zip

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpunit
      run: composer phpunit

  lint:
    name: Run PHP Lint
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd, mysqli, opcache, zip

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phplint
      uses: overtrue/phplint@9.4
      with:
        path: app/
        options: --exclude=*.log --exclude=vendor

  php-cs-fixer:
    name: PHP CS Fixer (Code Style)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd, mysqli, opcache, zip

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP CS Fixer (dry-run)
      run: composer csfix-dry

  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd, mysqli, opcache, zip

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: composer phpstan
